library(shiny)

shinyUI(fluidPage(
  

  titlePanel("Distribution Explorer"),

  sidebarLayout(
    sidebarPanel(style = "overflow-y:scroll; max-height: 600px",
      sliderInput("mn","Min x:",min = -100,max = -1,value = -2, step=1),
      sliderInput("mx","Max x:",min = 1,max = 100,value = 2, step=1),
      sliderInput("my","Max y:",min = 0.01,max = 2,value = 0.5),
      radioButtons("numdist", "How many distributions?",choices=c(1,2,3),inline = TRUE),
      radioButtons("distribution1",
                   "Choose Distribution",
                   choices = c("normal","uniform","poisson","binomial","exponential",
                               "student (t)","chi-squared"),
                   selected = "normal",
                   inline = TRUE),
      conditionalPanel(condition = "input.distribution1 == 'normal'",
       sliderInput("meanN","Mean:",min = -10,max = 10,value = 0),
       sliderInput("sdevN","Standard deviation:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution1 == 'uniform'",
       sliderInput("minU","Minimum:",min = -10,max = 0,value = -5),
       sliderInput("maxU","Maximum:",min = 0,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution1 == 'poisson'",
       sliderInput("rateP","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution1 == 'binomial'",
       sliderInput("sizeB","Size:",min = 1,max = 10,value = 4),
       sliderInput("probB","Probability:",min = 0,max = 1,value = 0.5)),
      conditionalPanel(condition = "input.distribution1 == 'exponential'",
       sliderInput("rateX","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution1 == 'student (t)'",
       sliderInput("ncenT","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfT","Degrees of freedom:",min = 1,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution1 == 'chi-squared'",
       sliderInput("ncenC","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfC","Degrees of freedom:",min = 1,max = 10,value = 5)),
      
      conditionalPanel(condition="input.numdist > 1",
      radioButtons("distribution2",
                   "Choose Distribution 2",
                   choices = c("normal","uniform","poisson","binomial","exponential",
                               "student (t)","chi-squared"),
                   selected = "normal",
                   inline = TRUE),
      conditionalPanel(condition = "input.distribution2 == 'normal'",
       sliderInput("meanN2","Mean:",min = -10,max = 10,value = 0),
       sliderInput("sdevN2","Standard deviation:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution2 == 'uniform'",
       sliderInput("minU2","Minimum:",min = -10,max = 0,value = -5),
       sliderInput("maxU2","Maximum:",min = 0,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution2 == 'poisson'",
       sliderInput("rateP2","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution2 == 'binomial'",
       sliderInput("sizeB2","Size:",min = 1,max = 10,value = 4),
       sliderInput("probB2","Probability:",min = 0,max = 1,value = 0.5)),
      conditionalPanel(condition = "input.distribution2 == 'exponential'",
       sliderInput("rateX2","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution2 == 'student (t)'",
       sliderInput("ncenT2","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfT2","Degrees of freedom:",min = 1,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution2 == 'chi-squared'",
       sliderInput("ncenC2","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfC2","Degrees of freedom:",min = 1,max = 10,value = 5))),
      
      conditionalPanel(condition="input.numdist > 2",
      radioButtons("distribution3",
                   "Choose Distribution 3",
                   choices = c("normal","uniform","poisson","binomial","exponential",
                               "student (t)","chi-squared"),
                   selected = "normal",
                   inline = TRUE),
      conditionalPanel(condition = "input.distribution3 == 'normal'",
       sliderInput("meanN3","Mean:",min = -10,max = 10,value = 0),
       sliderInput("sdevN3","Standard deviation:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution3 == 'uniform'",
       sliderInput("minU3","Minimum:",min = -10,max = 0,value = -5),
       sliderInput("maxU3","Maximum:",min = 0,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution3 == 'poisson'",
       sliderInput("rateP3","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution3 == 'binomial'",
       sliderInput("sizeB3","Size:",min = 1,max = 10,value = 4),
       sliderInput("probB3","Probability:",min = 0,max = 1,value = 0.5)),
      conditionalPanel(condition = "input.distribution3 == 'exponential'",
       sliderInput("rateX3","Rate:",min = 0.1,max = 10,value = 1)),
      conditionalPanel(condition = "input.distribution3 == 'student (t)'",
       sliderInput("ncenT3","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfT3","Degrees of freedom:",min = 1,max = 10,value = 5)),
      conditionalPanel(condition = "input.distribution3 == 'chi-squared'",
       sliderInput("ncenC3","Non-centrality:",min = -37,max = 37,value = 0),
       sliderInput("dfC3","Degrees of freedom:",min = 1,max = 10,value = 5)))
    ),
    
    # Show a plot of the generated distributions
    mainPanel(
       plotOutput("distPlot")
    )
  )
))